### ISSUE TITLE
Error computing expected influence from case-dropping bootstrap 

### ISSUE THREAD

**Issue by brklynn** [SachaEpskamp/bootnet#33]
Hi,

I am getting an error somewhat similar to a few mentioned here when trying to bootstrap centrality indices- specifically, expected influence.

My data is ordinal ranging from 0 to 8 (beyond what is automatically detected by corAuto), so I used the custom function below. 

function0 <- function(symdata){
  EBICglasso(cor(symdata,method="spearman",use="pairwise.complete.obs"),
             nrow(symdata),gamma=0)}
net0 <- estimateNetwork(symdata,default="none",fun=function0)

Going on to bootstrap my results, I can successfully bootstrap the edges and even strength, closeness, and betweenness. 

net0_boot_centrality <- bootnet(net0, nBoots = 1000, type = "case", 
                                statistics = c("strength","betweenness","closeness"))

However, when I try to look at expected influence, I get the following error while bootstrapping:
Error in eigen(S) : infinite or missing values in 'x'

and the following error when computing statistics:
Error in data.frame(name = name, type = "expectedInfluence", node1 = x[["labels"]],  : 
  arguments imply differing number of rows: 1, 17, 0

I have tried different bootnet argument variations with the same result.  Any help would be greatly appreciated!

Brooklynn

**Comment by dpmoriarity** [comment]
I received the same error: " in data.frame(name = name, type = "expectedInfluence", node1 = x[["labels"]],  : 
 arguments imply differing number of rows: 1, 18, 0") when running a case-dropping bootstrap. The nonparametric bootstrap ran fine. I was also using a custom function (code for function, network, and bootstraps below)

lasso_function <- function(data){EBICglasso(cor(data,use="complete.obs", method="spearman"), n = nrow(data))}

T1Data_S_network<- estimateNetwork(T1Data_S,default="none",fun=lasso_function)

b1  <- bootnet(T1Data_S_network, nBoots = 1000,statistics=c("edge","strength","expectedInfluence"), labels = labels_S, type = "nonparametric")
b2 <- bootnet(T1Data_S_network, nBoots = 1000, statistics=c("edge","strength","expectedInfluence"), labels = labels_S, type = "case")

**Comment by brklynn** [comment]
I can also run nonparametric as well. It seems unique to the combination of case + expected influence. Hopefully this can get elucidated for us.

**Comment by mayakup** [comment]
Hi all,

I noticed I tend to receive this error message when I bootstrap a network that often returns empty. Did you come across a similar pattern?

**Comment by dpmoriarity** [comment]
I didn't personally get any warnings or errors to that effect when using estimatenetwork or during the bootstrapping procedure.

**Comment by dpmoriarity** [comment]
Actually, sorry about that, wrong model. Yes, the bootstrapping procedure is giving me warnings about empty networks being selected as the best fitting models (this came up eight times). This warning only comes up in the case dropping bootstrap.

**Comment by SachaEpskamp** [comment]
Hi all,

This should now be resolved in the devel version on Gtihub. Could anyone check? Then I'll submit it to CRAN.
```

library("devtools")
install_github("sachaepskamp/bootnet")
```

Best, Sacha

**Comment by dpmoriarity** [comment]
Thanks, Sacha. I'm still getting the same error. Not sure if this is useful information but I got this message while updating.

Error: Failed to install 'bootnet' from GitHub:
  (converted from warning) package ‘foreach’ is in use and will not be installed.

**Comment by brklynn** [comment]
Sacha,

It worked for me! 

Notably, when trying to download the Github version of bootnet, I also received many errors similar to what Dan is mentioning. For example: Error: Failed to install 'bootnet' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘backports’

How I fixed this was by installing each package it was trying to remove 
e.g. install.packages("backports")

Once I did this for digest, Rccp, and backports, the bootnet download went through, and I could perform the case-dropping bootstrap of expected influence successfully.

Thank you very much! Please let me know if I can help further.

Brooklynn

**Comment by dpmoriarity** [comment]
That worked for me too! Cleared the workspace and installed the problematic package by itself. However, I'm getting a similar error (potentially due to a different modeling issue) for a later bootstrapping procedure: This time it having issues with the strength metric. Also, it comes up with both the nonparametric and case-dropping bootstraps. It differs from the last network in that it is dense, so I'm not sure if this is driving the issue or not.


 Network with lowest lambda selected as best network: assumption of sparsity might be violated.
Computing statistics...
Error in data.frame(name = name, type = "strength", node1 = x[["labels"]],  : 
  arguments imply differing number of rows: 1, 18, 13

**Comment by SachaEpskamp** [comment]
Thanks! I will close this issue then. Perhaps you can open a new issue about the new message? Do you get it when bootstrapping or when estimating the original network?
