### ISSUE TITLE
object 'bridgeCentralityNames' not found

### ISSUE THREAD

**Issue by GerardYu** [SachaEpskamp/bootnet#56]
hi there,

i used to able to run

T1NETboot<-bootnet(data.matrix(T1NET), nBoots=1000, default = "EBICglasso",corMethod = "cor", signed=T, weighted= T, missing="pairwise", statistics=c("edge","strength"), nCores = 5, type="case")

however, after i did an install_github("SachaEpskamp/bootnet") to update the package.

the above command resulted in the following error:

Note: bootnet will store only the following statistics:  edge, strength
Estimating sample network...
Estimating Network. Using package::function:
  - qgraph::EBICglasso for EBIC model selection
    - using glasso::glasso
Bootstrapping...
Error in get(name, envir = envir) : 
  argument "communities" is missing, with no default

so i saw your response to a similar issue raised previously, so i did this 

T1NET.est <- estimateNetwork(data.matrix(T1NET), default = "EBICglasso",corMethod="cor", weighted = T, signed=T)
T1NETboot<-bootnet(T1NET.est, nBoots=1000, statistics=c("edge","strength"), nCores = 5, type="case")

however i still got the same error

so i tried put in the communities to see if it works

T1NETboot<-bootnet(T1NET.est, nBoots=1000, statistics=c("edge","strength","bridgeStrength"), nCores = 5, type="case", communities = nodelabels$domain1, useCommunities = "all")

but i got another error instead

Note: bootnet will store only the following statistics:  edge, strength, bridgeStrength
Estimating sample network...
Estimating Network. Using package::function:
  - qgraph::EBICglasso for EBIC model selection
    - using glasso::glasso
Bootstrapping...
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01m 06s
Computing statistics...
  |+                                                 | 1 % ~51s          Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: object 'bridgeCentralityNames' not found

just fyi i was able to compute the bridge centrality without any issues using :
bridge(T1NET.est$graph,communities = nodelabels$domain1)

**Comment by SachaEpskamp** [comment]
@paytonjjones do you have an idea about this?

**Comment by SachaEpskamp** [comment]
We fixed the first error, and can't reproduce the second. @GerardYu can you check if it works now with the new devel version?

**Comment by GerardYu** [comment]
thanks. indeed, the first error is fixed for me too. However when i do the bootstrapping with bridge strength, i've encountered a new error

> T1NETboot<-bootnet(T1NET.est, nBoots=1000, statistics=c("edge","strength","bridgeStrength"), nCores = 5, type="case", communities = nodelabels$domain, useCommunities = "all")
Note: bootnet will store only the following statistics:  edge, strength, bridgeStrength
Estimating sample network...
Estimating Network. Using package::function:
  - qgraph::EBICglasso for EBIC model selection
    - using glasso::glasso
Bootstrapping...
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01m 11s
Computing statistics...
  |                                                  | 0 % ~calculating  Error in checkForRemoteErrors(val) : 
  one node produced an error: object 'bridgeCentralityNames' not found

**Comment by SachaEpskamp** [comment]
I think I fixed this, can you try now?

**Comment by GerardYu** [comment]
yes it works now. thanks

**Comment by JASPUSER09990** [comment]
Hi @SachaEpskamp, after installing bootnet & NetworkComparisonTest, this object-not-found issue still exists. Could you please take a look?

devtools::install_github("SachaEpskamp/bootnet")
devtools::install_github("SachaEpskamp/NetworkComparisonTest")
library(readr)
library(usethis)
library(devtools)
library(NetworkComparisonTest)
library(ggplot2)
library(qgraph)
library(huge)
library(bootnet)
> stability_c1 <- bootnet(c1netEST, nBoots = 1000, default="EBICglasso", nCores=8)
Note: bootnet will store only the following statistics:  edge, strength, outStrength, inStrength
Bootstrapping...
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=42s  
Computing statistics...
Error in quo_deparse(x, deparser) : unused argument (deparser)
> save(stability_c1, file = "stability_c1.Rfile")
Error in save(stability_c1, file = "stability_c1.Rfile") : 
  **object ‘stability_c1’ not found**
> load("stability_c1.Rfile")
Error in readChar(con, 5L, useBytes = TRUE) : **cannot open the connection**
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  **cannot open compressed file 'stability_c1.Rfile', probable reason 'No such file or directory'**

**Comment by SachaEpskamp** [comment]
Can you provide a reproducible example? for example, the code below works fine for me:

```
library(bootnet)
net <- estimateNetwork(matrix(rnorm(400),100,4), default = "EBICglasso")
boots <- bootnet(net, nBoots = 1000, nCores = 8)
```

**Comment by JASPUSER09990** [comment]
@SachaEpskamp Thanks. The bootstrapping works as before. The errors happen when I need to quote "boots", as shown in below (see, **save**, **plot**). Can you generate the pdf of the stability?

> net <- estimateNetwork(matrix(rnorm(400),100,4), default = "EBICglasso")
Estimating Network. Using package::function:
  - qgraph::EBICglasso for EBIC model selection
    - using glasso::glasso
An empty network was selected to be the best fitting network. Possibly set 'lambda.min.ratio' higher to search more sparse networks. You can also change the 'gamma' parameter to improve sensitivity (at the cost of specificity).
> boots <- bootnet(net, nBoots = 1000, nCores = 8)
Note: bootnet will store only the following statistics:  edge, strength, outStrength, inStrength
Bootstrapping...
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=05s  
Computing statistics...
**Error in quo_deparse(x, deparser) : unused argument (deparser)
> save(boots, file = "boots.Rfile")
Error in save(boots, file = "boots.Rfile") : object ‘boots’ not found
> load("boots.Rfile")**
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'boots.Rfile', probable reason 'No such file or directory'
> pdf("boots.pdf", height=30, width=25)
**> plot(boots, order = "sample")  # confidence intervals**
Error in plot(boots, order = "sample") : object 'boots' not found
> dev.off()
null device 
          1

**Comment by SachaEpskamp** [comment]
Can you include the output of `sessionInfo()`?

**Comment by JASPUSER09990** [comment]
[output.txt](https://github.com/SachaEpskamp/bootnet/files/6420714/output.txt)
Sure. Please find the output attached.

**Comment by SachaEpskamp** [comment]
So the line `bootnet(net, nBoots = 1000, nCores = 8)` gives this error for you? I can't really reproduce it... Perhaps try to reboot R, make sure the workspace is not loaded when loading R, update all packages via `update.packages(ask=FALSE)` and rerun the code I gave?
```
library(bootnet)
net <- estimateNetwork(matrix(rnorm(400),100,4), default = "EBICglasso")
boots <- bootnet(net, nBoots = 1000, nCores = 8)
```

**Comment by JASPUSER09990** [comment]
I did all these steps above, but it's strange that **Error in quo_deparse(x, deparser) : unused argument (deparser)** still exists. Maybe this explains why the **save** command doesn't work?

> boots <- bootnet(net, nBoots = 1000, nCores = 8)
Note: bootnet will store only the following statistics:  edge, strength, outStrength, inStrength
Bootstrapping...
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=06s  
Computing statistics...
Error in quo_deparse(x, deparser) : unused argument (deparser)

**Comment by SachaEpskamp** [comment]
If this line gives an error then indeed all further lines won't work either. Can you try to run this with `nCores = 1`?

**Comment by JASPUSER09990** [comment]
The same error message identified.
[output2.txt](https://github.com/SachaEpskamp/bootnet/files/6421085/output2.txt)

**Comment by SachaEpskamp** [comment]
I don't really understand the problem, sorry. There seems to be some issue with a dependency. But I can't reproduce the problem myself (just installed the latest R version and new packages). Can you try to update the `rlang` package perhaps?

**Comment by JASPUSER09990** [comment]
Yes. A confusing case. I simply needed to test the network stability. But interestingly I could successfully get the graphs from JASP, another bootnet-based program. :)
